#### User Registration
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "userName": "Minnie",
    "userEmail": "minnie@gmail.com",
    "roleName": "Gov-Official",
    "upassword":"Qwerty@123",
    "termsAccepted": "true"
}



####User Approval
POST http://localhost:4000/auth/approveUser
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJjZTExMzY2Ny05OWMxLTRkYmItOTVlYS0xOWRjYWIwZWY2NGMiLCJ1c2VyTmFtZSI6IkphbmUgV2FpbmFpbmEiLCJyb2xlTmFtZSI6IkFkbWluIiwiaWF0IjoxNzIxNjcyNDc4LCJleHAiOjE3MjE3MDg0Nzh9.1JCM7BuMTOPQs1N7vb8US4hWUecYlnHttPaQGixXcFg
Content-Type: application/json

{
    "userId": "f203f89a-8f16-4a2f-be9d-bc012d2fdbf6"
}


#### Gov-Official Signup notifications
GET http://localhost:4000/auth/gov-OfficialRequests



#### User Login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "userEmail": "jw@gmail.com",
    "upassword": "Qwerty@123"
}



#### All Users
GET http://localhost:4000/auth/users
# token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJmNTVmMGE2OS1jNmE5LTQyM2YtOTVmZS0yYzM4MDgyNGZmODAiLCJ1c2VyTmFtZSI6Ik1lcmN5IE9mZmljaWFsIiwiaWF0IjoxNzIxNTUxNDYzLCJleHAiOjE3MjE1ODc0NjN9.j_TYl7qOkhS4VoKM2k-9nTu8qR__vPHovjaM2Qjk610



#### A User
GET http://localhost:4000/auth/f0732089-3d9b-43c2-902d-d806e3cdae5d


#### Delete User
DELETE  http://localhost:4000/auth/75654b89-19b5-44a3-969f-b4bf99fbf7c7
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJjZTExMzY2Ny05OWMxLTRkYmItOTVlYS0xOWRjYWIwZWY2NGMiLCJ1c2VyTmFtZSI6IkphbmUgV2FpbmFpbmEiLCJyb2xlTmFtZSI6IkFkbWluIiwiaWF0IjoxNzIxODk3MjEyLCJleHAiOjE3MjE5MzMyMTJ9.zjGqy-Q-AJNkc-WgJdT_I8pfvDhKSQe3s2ZefNbEhU0


####Getting deleted users
GET http://localhost:4000/auth/deletedUsers



### Request for Password-Reset
POST http://localhost:4000/auth/reset-password-request
Content-Type: application/json

{
  "userEmail": "mercywainaina993@gmail.com"
}



### Reset Password
POST http://localhost:4000/auth/reset-password
Content-Type: application/json

{
  "resetToken": "e8e13e9221a8efeae427216fb0183a6c72ded9d106cf467de5026ccea82e2fcd",
  "newPassword": "Secure@123"
}





#### Adding a View
POST http://localhost:4000/view
# token:789fccd8-be96-46d9-9921-31e327db1976
Content-Type: application/json

{
    "userId": "b9843f89-71c0-49b1-9d71-1f580b7cc260",
    "userName": "Alice",
    "viewContent": "Peacefull protests"
}

#### All Views
GET http://localhost:4000/view
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJjZTExMzY2Ny05OWMxLTRkYmItOTVlYS0xOWRjYWIwZWY2NGMiLCJ1c2VyTmFtZSI6IkphbmUgV2FpbmFpbmEiLCJyb2xlTmFtZSI6IkFkbWluIiwiaWF0IjoxNzIyMjQyOTkwLCJleHAiOjE3MjIyNzg5OTB9.8swGVF-tdApzZmT-u-97hccJddbQBxGB61hSN45NfRA


#### Single-View
GET http://localhost:4000/view/bd4359ad-6d1d-4475-b1a0-98c17db4a35d


#### Deleting a View
DELETE http://localhost:4000/view/bd4359ad-6d1d-4475-b1a0-98c17db4a35d
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJjZTExMzY2Ny05OWMxLTRkYmItOTVlYS0xOWRjYWIwZWY2NGMiLCJ1c2VyTmFtZSI6IkphbmUgV2FpbmFpbmEiLCJyb2xlTmFtZSI6IkFkbWluIiwiaWF0IjoxNzIyMjQyOTkwLCJleHAiOjE3MjIyNzg5OTB9.8swGVF-tdApzZmT-u-97hccJddbQBxGB61hSN45NfRA

#### Updating a View
PATCH http://localhost:4000/view/bd4359ad-6d1d-4475-b1a0-98c17db4a35d
Content-Type: application/json

{
    "userId":"f0732089-3d9b-43c2-902d-d806e3cdae5d",
    "viewContent": "Anguka Nayo"
}





#### Adding an Incident
POST http://localhost:4000/incident
Content-Type: application/json

{
    "userId": "5734a056-f5b0-48aa-b580-08b98b5e2987",
    "userName": "Alice",
    "incidentImg": "https://canva.com/content-partner/?utm_medium=partner&utm_source=pixabay&utm_campaign=retouch_in_canva_edit_image&image-url=https%3A//pixabay.com/get/gab20ff6610f2b24de7ab41116a15b6be0696ad5dc7d040c0055fb3bb4813223eb1268afca1cf7fad2c7cc143c3689ff7_1920.jpg%3Flonglived%3D&external-id=6780743&canva-media-id=",
    "incidentDesc": "A night of terror in Zimmerman"
}

#### All Incidents
GET http://localhost:4000/incident
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJiOTg0M2Y4OS03MWMwLTQ5YjEtOWQ3MS0xZjU4MGI3Y2MyNjAiLCJ1c2VyTmFtZSI6IkpvbmF0aGFuIiwicm9sZU5hbWUiOiJHb3YtT2ZmaWNpYWwiLCJpYXQiOjE3MjE5MDY1MTksImV4cCI6MTcyMTk0MjUxOX0.Z3HrCqkZVSxKVrQkbl1v4gBwpB-jeflIzdKgCT00k-M


###A single Incident
GET http://localhost:4000/incident/c7aad8b0-d241-4a31-bb3e-9d8dd7426610


####Update Incident
PATCH http://localhost:4000/incident/c7aad8b0-d241-4a31-bb3e-9d8dd7426610
Content-Type: application/json

{
    "userId": "ee310da2-0611-400a-b557-af1102cdcd97",
    "incidentImg": "https://canva.com/content-partner/?utm_medium=partner&utm_source=pixabay&utm_campaign=retouch_in_canva_edit_image&image-url=https%3A//pixabay.com/get/gab20ff6610f2b24de7ab41116a15b6be0696ad5dc7d040c0055fb3bb4813223eb1268afca1cf7fad2c7cc143c3689ff7_1920.jpg%3Flonglived%3D&external-id=6780743&canva-media-id=",
    "incidentDesc": "Several Casualties in todays protests"
}


#### Delete Incident
DELETE http://localhost:4000/incident/c7aad8b0-d241-4a31-bb3e-9d8dd7426610





###Adding a poll
POST http://localhost:4000/poll
Content-Type: application/json

{
    "userId": "b9843f89-71c0-49b1-9d71-1f580b7cc260",
    "pollQuestion": "Do you believe that police departments should be present at protests in an effort to stop them or to ensure that people are allowed to express their views safely",
    "pollOptions": ["Yes", "No", "Not sure"],
    "pollStatus": "Active"
}


####All Polls
GET http://localhost:4000/poll
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJiOTg0M2Y4OS03MWMwLTQ5YjEtOWQ3MS0xZjU4MGI3Y2MyNjAiLCJ1c2VyTmFtZSI6IkpvbmF0aGFuIiwicm9sZU5hbWUiOiJHb3YtT2ZmaWNpYWwiLCJpYXQiOjE3MjE5MDY1MTksImV4cCI6MTcyMTk0MjUxOX0.Z3HrCqkZVSxKVrQkbl1v4gBwpB-jeflIzdKgCT00k-M


#### Single Poll
GET http://localhost:4000/poll/29c4b046-ffd8-4217-9d5e-b29fa1d68584



####Update Poll
PATCH http://localhost:4000/poll/c7aad8b0-d241-4a31-bb3e-9d8dd7426610
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJiOTg0M2Y4OS03MWMwLTQ5YjEtOWQ3MS0xZjU4MGI3Y2MyNjAiLCJ1c2VyTmFtZSI6IkpvbmF0aGFuIiwicm9sZU5hbWUiOiJHb3YtT2ZmaWNpYWwiLCJpYXQiOjE3MjE5MDY1MTksImV4cCI6MTcyMTk0MjUxOX0.Z3HrCqkZVSxKVrQkbl1v4gBwpB-jeflIzdKgCT00k-M

{
    "userId": "ee310da2-0611-400a-b557-af1102cdcd97",
    "pollQuestion": "Do you believe that police departments should be present at protests in an effort to stop them or to ensure that people are allowed to express their views safely",
    "pollOptions": ["Yes", "No", "Not sure"],
    "pollStatus":"Active"
}


####Deleting a poll
DELETE http://localhost:4000/poll/6cfd6e86-69ec-434c-9570-22aeff7abbc4



